image: node:lts

stages:
  - test
  - build
  - deploy

variables:
  PRODUCTION_DOMAIN: https://justinstephenson.github.io/Rock-Paper-Scissors-React
  GIT_DOMAIN: https://$USER_NAME:$USER_TOKEN@github.com/JustinStephenson/Rock-Paper-Scissors-React.git

black box tests:
  stage: test
  script:
    - npm install
    - npm test

build website:
  stage: build
  only:
  - main
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - ./build

deploy production:
  stage: deploy
  only:
    - main
  environment:
    name: production github-pages
    url: $PRODUCTION_DOMAIN
  before_script:
    - git config --global user.name "$USER_NAME"
    - git config --global user.email "$USER_EMAIL"
    - git remote rm origin
    - git remote add origin $GIT_DOMAIN
  script:
    - npm install
    - npm install -g gh-pages
    - gh-pages -d build
